# Generated by Django 5.0 on 2024-02-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is published'),
        ),
    ]
